name: Post-Template Initialization
on:
  push:
    branches:
      - main
      - master

jobs:
  setup:
    if: github.run_number == 1 && github.repository != 'FriquetLuca/react_gh_page'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Replace placeholders
        run: |
          # 1. Define variables for clarity
          NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          URL="https://${OWNER}.github.io/${NAME}/"
          PRETTY_NAME=$(echo "$REPO_NAME" | sed 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++) \$i=toupper(substr(\$i,1,1)) substr(\$i,2)}1')

          sed -i "s/TEMPLATE_PRETTY_NAME/$PRETTY_NAME/g" README.md index.html
          sed -i "s/TEMPLATE_NAME/${NAME}/g" README.md package.json vite.config.ts

          # 3. Replace Owner
          sed -i "s/TEMPLATE_OWNER/${OWNER}/g" README.md package.json LICENSE

          # 4. Replace URL (using | as delimiter because URL contains slashes)
          sed -i "s|TEMPLATE_URL|${URL}|g" README.md
          
      - name: Cleanup and Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm .github/workflows/post-init.yml
          git add .
          # Check if there are changes before committing to avoid errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: initialize project" && git push)
